"""user model weight update

Revision ID: 576dcc99bbe1
Revises: 9dfcd76d493a
Create Date: 2024-06-14 18:57:34.986595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "576dcc99bbe1"
down_revision: Union[str, None] = "9dfcd76d493a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("weight", sa.Float(), nullable=True))
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "weight")
    # ### end Alembic commands ###
