"""user full_name nullable

Revision ID: 9dfcd76d493a
Revises: 0519370b936d
Create Date: 2024-06-04 19:05:19.433923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9dfcd76d493a"
down_revision: Union[str, None] = "0519370b936d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
